categorizacion_caletas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('criterios.urls')),

]

criterios/urls.py
from django.urls import re_path, include, path
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'grafica/$', views.grafica, name='grafica'), 
    re_path(r'data/', views.graficaData, name='data'), 
    
    re_path(r'resultado/categoryA/', views.resultadoA),
    re_path(r'resultado/categoryB/', views.resultadoB),
    re_path(r'resultado/categoryC/', views.resultadoC),
    re_path(r'form_eval$', views.criterios_list),
    re_path(r'prossc_eval$', views.prossc_eval),
    #botones de página principal
    re_path(r'register$', views.register),     
    re_path(r'addUsuario$', views.addUsuario, name='addUser'),
    
    #login y logout
    url( r'^login/$',auth_views.LoginView.as_view(template_name="iniciar.html"), name="login"),
    #url( r'^logout/$',auth_views.LoginView.as_view(template_name="iniciar.html"), name="logout"),
    re_path(r'logout/', views.logout_request, name="logout"),
    #olvidado password
    url(r'^',include('django.contrib.auth.urls')),
    
    #dashboard
    re_path(r'dash$', views.dash, name='dash'),
    re_path(r'^(?P<formulario_id>[0-9]+)/result_desembarco/$',views.re_desembarco, name='result_desembarco'),
    
    #result de agregar usuarios
    re_path(r'saveResult$', views.saveResult, name='save'),
    
    #resultadosxls y pdf
    re_path(r'resultadoxls$',views.re_xls),
    re_path(r'^reporte_formularios/$', views.ReporteFormulariosExcel.as_view(), name="reporte_formularios"),
    url(r'^upload/csv/$', views.upload_csv, name='upload_csv'),
  #  re_path(r'^ingresoBarco/$', views.ReporteFormulariosExcel.as_view(), name="ingresoBarco"),
    re_path(r'^csv/ingresoCSV/$', views.getBarcosParaCSV, name="ingresoCSV"),
 #   re_path(r'^reporte_formularios/$', views.ReporteFormulariosExcel.as_view(), name="reporte_formularios"),

    url(r'^vistaBarco$', views.getVistaCSV),

    url(r'^documentos/(?P<path>.*)$', views.downloadCSV),
    re_path(r'^reporte_formularios_pdf/(?P<formulario_id>[0-9]+)/$', views.ReporteFormulariosPDF.as_view(), name="reporte_formularios_pdf"),
    re_path(r'^reporte_grafica_pdf/$', views.ReporteGraficasPDF.as_view(), name="reporte_grafica"),    
    # url(r'^generate/pdf/$', views.generate_pdf, name='generate_pdf'),
]

criterios/models.py
from django.db import models

from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from math import floor

#VALIDADORES
def MaxValueValidator(value):
    if value > 100:
        raise ValidationError(
            _('%(value)s is not valid'),
            params={'value': value},
        )

def MinValueValidator(value):
    if value < 1:
        raise ValidationError(
            _('%(value)s is not valid'),
            params={'value': value},
        )


def roundDecimal(number, decs):    

    xmay = number*(10**(decs+1))
    xmen = number*(10**(decs))
    xmay = floor(xmay)
    xmen = floor(xmen)*10

    num_eval = xmay-xmen
    if num_eval <= 0:
        return round(number,4)

    inc = 0

    trunk_number = floor(number*(10**(decs)))
    trunk_number = trunk_number/(10**(decs))   

    if num_eval >=  5:
        inc = 1/(10**(decs))
        trunk_number = inc+trunk_number

    return round(trunk_number,4)


#Criterios
class Criterio(models.Model):


    idCriterio = models.AutoField(primary_key=True)
    idCriterioPadre = models.ForeignKey('self' , blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    children = models.IntegerField(default=0)

    porcentaje = models.IntegerField(
        default = 1,
        validators=[MaxValueValidator, MinValueValidator]
    )

    nivel = models.IntegerField(
        default = 0
    )

    multipleOptions = models.BooleanField( default=False)


    def getStr(self):
        return self.nombre

    def setChildren(self, children):
        self.children = children

    def getId(self):
        return self.idCriterio

    def getPorcentaje(self):
        return self.porcentaje

    def getNivel(self):
        return self.nivel

    def __init__(self, *args, **kwargs):
        super(Criterio, self).__init__(*args, **kwargs)
        if self.idCriterioPadre is not None:
            if self.nivel == 0:
                item = Criterio.objects.get(pk=self.idCriterioPadre.pk)
                self.nivel = item.nivel + 1




 #Condiciones
class Condicion(models.Model):
    idCondicion = models.AutoField(primary_key=True)
    idCriterio = models.ForeignKey(Criterio, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    porcentaje = models.IntegerField(
        default = 1,
        validators=[MaxValueValidator, MinValueValidator]
    )
    isSelected  = models.BooleanField(default=False)
    ponderado = models.DecimalField(
        default = 0.0,
        max_digits=5,
        decimal_places=4
    )

    def __str__(self):
        return self.nombre

    def getPorcentaje(self):
        return self.porcentaje

    def getPonderado(self):
        return self.ponderado

    def __init__(self, *args, **kwargs):
        super(Condicion, self).__init__(*args, **kwargs)
        if self.ponderado == 0.0:

            temp_pond = self.porcentaje
            crit1 = Criterio.objects.get(idCriterio=self.idCriterio.getId())
            div = 100**(crit1.getNivel()+2)

            while True:
                temp_pond *= crit1.getPorcentaje()
                if crit1.idCriterioPadre is None:
                    break
                crit2 = Criterio.objects.get(idCriterio=crit1.idCriterioPadre.pk)
                crit1 = crit2

            total = temp_pond/div

            self.ponderado = roundDecimal(total,4)


class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    usuario = models.CharField(max_length=100)
    dni = models.CharField(max_length=8)
    correo = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    instituto = models.CharField(max_length=100)  
    user =  models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
         return self.usuario


class Formulario(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)
    idFormulario = models.AutoField(primary_key=True)
    nombreFormulario = models.CharField(max_length=100)
    tipo = models.CharField(max_length=50)
    nivel = models.CharField(max_length=50)
    ponderado = models.CharField(max_length=5,blank=True,null=True)
    condiciones = models.CharField(max_length=200,blank=True,null=True)

    def __str__(self):
         return self.nombreFormulario 

class CSV(models.Model):
    idCSV = models.AutoField(primary_key=True)

    nombreArchivo = models.CharField(max_length=50)
    eliminados1 = models.IntegerField(default=0)
    eliminados2 = models.IntegerField(default=0)
    eliminados3 = models.IntegerField(default=0)
    eliminados4 = models.IntegerField(default=0)

    def __str__(self):
         return str("{:10.4f}".format(self.eslora))+str("{:10.4f}".format(self.manga))+str("{:10.4f}".format(self.puntal))




class Barco(models.Model):
    matricula = models.CharField(max_length=50)
    csv = models.ForeignKey(CSV, on_delete=models.CASCADE, blank=True, null=True)

    casco = models.CharField(max_length=50)
    regimen =  models.CharField(max_length=50)
    tipo =  models.CharField(max_length=50)
    eslora  =  models.DecimalField(max_digits=5, decimal_places=2)
    manga  =models.DecimalField(max_digits=5, decimal_places=2)
    puntal =models.DecimalField(max_digits=5, decimal_places=2)
#    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
         return str("{:10.4f}".format(self.eslora))+str("{:10.4f}".format(self.manga))+str("{:10.4f}".format(self.puntal))

criterios/forms.py
from django import forms

class RegistrationForm(forms.Form):
	nombre = forms.CharField(max_length=100,
							widget=forms.TextInput(attrs={'id': 'username-input','class': 'username-input',
														'placeholder': 'Nombre'}))

	apellido = forms.CharField(max_length=100,
							widget=forms.TextInput(attrs={'id': 'username-input','class': 'username-input',
														'placeholder': 'Apellido'}))

	usuario = forms.CharField(max_length=100,
							widget=forms.TextInput(attrs={'id': 'username-input','class': 'username-input',
														'placeholder': 'Usuario'}))

	dni = forms.CharField(max_length=8,
							widget=forms.TextInput(attrs={'id': 'username-input','class': 'username-input',
														'placeholder': 'Dni'}))

	correo = forms.CharField(max_length=100,
							widget=forms.EmailInput(attrs={'id': 'username-input','class': 'username-input',
														'placeholder': 'Correo'}))

	password = forms.CharField(max_length=100,
							widget=forms.PasswordInput(attrs={'id': 'password_input','class': 'password_input',
														'placeholder': 'Contraseña'}))
	"""
	passwordseg = forms.CharField(max_length=100,
							widget=forms.PasswordInput(attrs={'id': 'password_input','class': 'password_input',
														'placeholder': 'Contraseña'}))
	"""
	instituto = forms.CharField(max_length=100,
							widget=forms.TextInput(attrs={'id': 'username-input','class': 'username-input',
														'placeholder': 'Institución'}))
	"""
	def clean_passwordseg(self):
		contra = self.cleaned_data.get("password")
		contra2 = self.cleaned_data.get("passwordseg")
		if contra in contra2:
			if contra2 != contra:
				raise forms.ValidationError("Las contraseñas no son iguales")
		return contra
"""
							
class LoginForm(forms.Form):
	usuario = forms.CharField(max_length=100,
							widget=forms.TextInput(attrs={'id':'username_input','class':'username-input',
														'placeholder':'Usuario'}))
	contra = forms.CharField(max_length=100,
							widget=forms.PasswordInput(attrs={'id': 'password_input','class': 'password_input',
														'placeholder': 'Contraseña'}))

class ResultForm(forms.Form):
	nombreFormulario = forms.CharField(max_length=100,
							widget=forms.TextInput(attrs={'id': 'username_input','class':'username-input',
														'placeholder':'Nombre'}))
		

criterios/templates/barcosParaCSV.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/cssParaTablas.css' %}" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'css/fondodash.css' %}" /> 
  
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<style>
.hidden{
    display:none;
}
.unhidden{
    display:block;
}
.main {
  padding: 16px;
  margin-top: 30px;
}
</style>

   <script type="text/javascript">
function goToByScroll(id) {
    // Remove "link" from the ID
    id = id.replace("link", "");
    // Scroll
    $('html,body').animate({
        scrollTop: $("#" + id).offset().top
    }, 'slow');
}
$(document).ready(function(){
  var contarDatos = 0 ;
  $("#ingresoDatosbtn").click(function(){
    $("#ingresoDatos").addClass("unhidden");
    $("#ingresoDatos").removeClass("hidden");
    $("#ingresoDatosbtn").addClass("btn-primary");
    $("#ingresoDatosbtn").removeClass("btn-default");
    $("#ingresoDatos").focus();
    $("#mostrar").addClass("hidden");
    $("#mostrar").removeClass("unhidden");
    $("#mostrarbtn").addClass("btn-default");
    $("#mostrarbtn").removeClass("btn-primary");
    $("#visualizar").addClass("hidden");
    $("#visualizar").removeClass("unhidden");
    $("#visualizarbtn").addClass("btn-default");
    $("#visualizarbtn").removeClass("btn-primary");
  });
   var contarMostrar = 0 ;
  $("#mostrarbtn").click(function(){
    $("#mostrar").addClass("unhidden");
    $("#mostrar").removeClass("hidden");
    $("#mostrarbtn").addClass("btn-primary");
    $("#mostrarbtn").removeClass("btn-default");
    $("#visualizar").addClass("hidden");
    $("#visualizar").removeClass("unhidden");
    $("#visualizarbtn").addClass("btn-default");
    $("#visualizarbtn").removeClass("btn-primary");
    $("#ingresoDatos").addClass("hidden");
    $("#ingresoDatos").removeClass("unhidden");
    $("#ingresoDatosbtn").addClass("btn-default");
    $("#ingresoDatosbtn").removeClass("btn-primary");
  });
   var contarVisualizar = 0 ;
  $("#visualizarbtn").click(function(){
    $("#visualizar").addClass("unhidden");
    $("#visualizar").removeClass("hidden");
    $("#visualizarbtn").addClass("btn-primary");
    $("#visualizarbtn").removeClass("btn-default");
    $("#mostrar").addClass("hidden");
    $("#mostrar").removeClass("unhidden");
    $("#mostrarbtn").addClass("btn-default");
    $("#mostrarbtn").removeClass("btn-primary");
    $("#ingresoDatos").addClass("hidden");
    $("#ingresoDatos").removeClass("unhidden");
    $("#ingresoDatosbtn").addClass("btn-default");
    $("#ingresoDatosbtn").removeClass("btn-primary");
  });
});
</script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
        <a class="navbar-brand">Bienvenid@:{{user}}</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
                <div class="btn-group" role="group" aria-label="Basic example">
                  <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'grafica'%}" role= "button">Estadísticos</a>
                  <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'dash'%}" role= "button">Dashboard</a>
                  <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'logout'%}" >Salir</a>
                </div>
            </ul>
          </div>
    </nav>

  <article>
<nav class="navbar-light bg-secondary-light">
   <div class="col-md-12 d-flex justify-content-center">
    <h2>Clasificación de Embarcaciones Artesanales</h2>
   </div>
    <div class="col-md-12 d-flex justify-content-center">
<div class="btn-group btn-group-justified" role="group" aria-label="...">


    {% if uploaded_file_url %}
     <button id ="ingresoDatosbtn"  type="button" class="btn btn-default">Ingreso de datos </button>
  <button id = "mostrarbtn" type="button" class="btn btn-default">Mostrar Información Filtrada</button>
  <button id = "visualizarbtn" type="button" class="btn btn-default">Graficar Data</button>


    {% endif %}

</div>
        </div>
</nav>
<div class="container">

  {% if uploaded_file_url == None  %}
<br>
    <br>
    <div id = "ingresoDatos" class="row">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

      <input type="file" name="myfile">
      <input type="submit" class="btn btn-secondary" value="Subir"></input>

</form>
      <p>Data de muestra en : <a href="../../documentos/databarcos.csv">databarcos.csv</a></p>


</div>

    {% endif %}




  {% if uploaded_file_url %}


    <div id = "ingresoDatos" class="row hidden">

                    <h2>Ingreso de datos</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

      <input type="file" name="myfile">

    <button type="submit">Subir</button>
</form>
               <p>Data de muestra en : <a href="../../documentos/databarcos.csv">databarcos.csv</a></p>
        <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>


</div>

    <div id ="mostrar" class="hidden">
        <br>
        <br>
        <div class="row">

        <div class="table-wrapper-scroll-y my-custom-scrollbar">

  <table class="table table-bordered table-striped mb-0">
    <thead>
      <tr>
        <th scope="col">#</th>

        <th scope="col">Nombre de Embarcacion</th>
        <th scope="col">Matricula</th>
        <th scope="col">Regimen</th>
        <th scope="col">Eslora</th>
        <th scope="col">Manga</th>
        <th scope="col">Puntal</th>
        <th scope="col">Capacidad de Bodega</th>
        <th scope="col">Permiso de Pesca</th>

      </tr>
    </thead>
    <tbody>
{% for indice,nombre,matricula,regimen,eslora,manga,puntal,bodega,permiso in z %}
      <tr>
        <th scope="row">{{indice}}</th>
        <td>{{nombre}}</td>

          <td>{{matricula}}</td>
          <td>{{regimen}}</td>
        <td>{{eslora}}</td>
          <td>{{manga}}</td>
        <td>{{puntal}}</td>
                    <td>{{bodega}}</td>
        <td>{{permiso}}</td>
      </tr>
    {% endfor %}

    </tbody>
  </table>
            </div>
    </div>
        <br>
        <br>
        <div class="row">
        <div class="col-md-12 d-flex align-middle  justify-content-center">
                <h3>Descripción Eliminados</h3>
            </div>
        </div>


        <div class="row">

            <div class="col-md-6">
<br>
                <br>
                <ul >
<li>Eliminación de datos imposibles son la
negatividad de las variables, valores
vacio . y el valor altamente amplio del
puntal:{{e1}}</li>
 <li>Eliminación de datos ilógicos por
razones de lógica descrito en la relación
entre la manga y la eslora  {{e2}}</li>
 <li>Eliminación de datos que pertenezcan a
embarcaciones no clasificadas en
artesanales:{{e3}}</li>
 <li>Eliminación de datos que contradicen las
medidas descritas en el paper:{{e4}} </li>
</ul>
       </div>
        <div class="col-md-6">


<img src="{% static 'img/histogramaEliminados.png' %}" class="img-fluid" alt="Responsive image">
            </div>
</div>
    </div>
    <div id = "visualizar" class="hidden">



<div class="row">

<div class="col-md-8">
    <br>
    <br>
<img src="{% static 'img/histograma.png' %}" class="img-fluid" alt="Responsive image">
</div>

<div class="col-md-4">
    <br>
    <br>
    <br>
    <h4> Distribución de Embarcaciones</h4>
    <table class="table">

  <tbody>
    <tr class = "categoria1">
      <th scope="row">Categoria 1 </th>
      <td>{{l1}}</td>
    </tr>
    <tr class = "categoria2">
      <th scope="row">Categoria 2 </th>
      <td>{{l2}}</td>
    </tr>
    <tr class = "categoria3">
      <th scope="row">Categoria 3 </th>
      <td>{{l3}}</td>
    </tr>
    <tr class = "categoria4">
      <th scope="row">Categoria 4 </th>
      <td>{{l4}}</td>
    </tr>
    <tr class = "categoria5">
      <th scope="row">Sin Categoria </th>
      <td>{{l5}}</td>
    </tr>
<tr class = "categoria5">
      <th scope="row">Total </th>
      <td>{{total}}</td>
    </tr>

   </tbody>
</table>

</div>
</div>

 </div>

    {% endif %}

    </div>
{% block js %}
{% endblock %}
{% block extrajs %}
{% endblock %}
</article>
</body>
</html> 

criterios/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static 'css/form_crit.css' %}" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'css/fondodash.css' %}" />  
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<style>
table {
    width: 100%; 
    /*border-radius: 10px; 
    box-shadow: 1px 1px 0 rgba(110, 107, 107, 0.1);*/
    margin: 1em auto;
    overflow: hidden; 
    text-align: center;
}
td{
  text-align: center;
  vertical-align: middle;
}
.cols {
  height: 600px;
  }
.izquier {
  position: left;
  width: 20%;
  padding-top:50px;
  padding-left: 30px;
  }
.container {
  width: 50%;
  }
.izquier,
.container {
  display: inline-table;
  height: 100%;
  }
.hidden{
    display:none;
}
.unhidden{
    display:block;
}
</style>
<script type="text/javascript">
$(document).ready(function(){
  var contarMaria = 0 ;
  $("#funciona").click(function(){
    contarMaria = contarMaria +1 ;
    if (contarMaria %2 ==1){
    $("#maria").addClass("unhidden");
    $("#maria").removeClass("hidden");
    $("#funciona").addClass("btn-secondary");
    $("#funciona").removeClass("btn-primary");
    }
    else{
    $("#maria").addClass("hidden");
    $("#maria").removeClass("unhidden");
    $("#funciona").addClass("btn-primary");
    $("#funciona").removeClass("btn-secondary");
    }
$("#maria").attr("disabled", true);
  });
    var contarElvis = 0 ;
    $("#funciona2").click(function(){
    contarElvis = contarElvis +1;
    if (contarElvis % 2==1){
    $("#elvis").addClass("unhidden");
    $("#elvis").removeClass("hidden");
    $("#funciona2").addClass("btn-secondary");
    $("#funciona2").removeClass("btn-primary");
      }else{
    $("#elvis").addClass("hidden");
    $("#elvis").removeClass("unhidden");
    $("#funciona2").addClass("btn-primary");
    $("#funciona2").removeClass("btn-secondary");
  }
  });
  var category;
    $('radio[name="category"]').click(function(){
      category=this.value;
    });
});
</script>

<body>
	
 <nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
    <a class="navbar-brand">Bienvenid@:{{user}}</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
            <div class="btn-group" role="group" aria-label="Basic example">
               <a id="resultado" class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'grafica'%}" role= "button">Estadísticos</a>
		           <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'logout'%}" >Salir</a>
            </div>
        </ul>
      </div>
  </nav>

  <div class = "cols">
  <div class="izquier">
    <p>Propuesta 1 :</p>
    <p>Clasificación de los Desembarcaderos</p> 
    <p>Propuesta 2 :</p>
    <p>Evaluación de los DPAS</p>
  </div>
	<div id="content" class="container">
     <div class="row">
        <input id ="funciona2" type="button"  class ="btn btn-primary" onclick="unhide(this, 'about') " name="Propuestaone" value="Propuesta 1">
        <input id ="funciona" type="button" class ="btn btn-primary " onclick="unhide(this, 'about') " name="Propuestaone" value="Propuesta 2">
        
     </div>
		<div id="maria" class="hidden">
        <div id="crit_head" class="row">
			<h2>Evaluación de Desembarcaderos Pesqueros Artesanales</h2>	
		</div>
    <hr>
    <div class="d-flex justify-content-around">
        <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="form_eval" role= "button">Nuevo Formulario</a>
        <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="resultadoxls" role= "button">Resultados</a>
    </div>
		<div id ="results">
        <table>
          <tbody>
          {% for formulario in user.usuario.formulario_set.all %}  
          <tr>
    				<td><a>{{ forloop.counter }}. </a><a id="espaciodea" href="{% url 'result_desembarco' formulario.pk %}">{{ formulario.nombreFormulario }}</a></td>
            <td><a title="Descarga" href="{% url 'reporte_formularios_pdf' formulario.pk%}" target="_blank"><img width="30" src="{% static 'img/descarga.png' %}" alt="Descarga"/></a></td>
            <td><a title="Editar" href=" " target="_blank"><img width="30" src="{% static 'img/editar.png' %}" alt="Editar"/></a></td>
            <td><a title="Eliminar" href=" " target="_blank"><img width="30" src="{% static 'img/eliminar.png' %}" alt="Eliminar"/></a></td>
          </tr>
          {% endfor %}
          </tbody>
         </table>
    </div>
        </div>

        <div id="elvis" class="hidden">
            <div id="crit_head" class ="row" >
			    <h2>Clasificación de barcos</h2>
		    </div>
		    <hr>
            <div id = "result">
            <div class="d-flex justify-content-around">
                <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{%url 'upload_csv'%}" role= "button">Clasificar Embarcaciones</a>

				</div>
            </div>
        </div>
        </div>
  </div>
</body>
</html>

criterios/templates/delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

criterios/templates/resultadoxls.html
{% load static %}

<!DOCTYPE html>
<html>
 <head>
    <link rel="stylesheet" href="{% static 'css/xls.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/fondodash.css' %}" /> 
 </head>

 <body>
  {% csrf_token %}
  <nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
      <a class="navbar-brand">Bienvenid@:{{user}}</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
          data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
          aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
              <div class="btn-group" role="group" aria-label="Basic example">
                <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'grafica'%}" role= "button">Estadísticos</a>
                <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'dash'%}" role= "button">Dashboard</a>
                <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'logout'%}" >Salir</a>
              </div>
          </ul>
        </div>
  </nav>
   
    <table cellspacing="0">
      <tr>
         <th>Nombre DPA</th>
         <th>Tipo</th>
         <th>Nivel</th>
         <th>Ponderado</th>
      </tr>
    {% for formulario in user.usuario.formulario_set.all %}
      <tr>
         <td>{{ formulario.nombreFormulario }}</td>
         <td>{{ formulario.tipo}}</td>
         <td>{{ formulario.nivel}}</td>
         <td>{{ formulario.ponderado }}</td>
      </tr>
    {% endfor %}
    </table>
    <div id = "center">
        <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'reporte_formularios' %}" role= "button"> Descargar</a>  
    </div>
  </div>
</body>
</html>